baseurl = "https://nothingradical.blog"
languageCode = "en-us"
paginate = 5
title = "Nothing Radical"
copyright = "© Frawley CC BY-NC-ND 4.0"

[author]
    name = "Frawley"
    email = "frawleyskid@gmail.com"
