main: []
social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/frawleyskid/nothingradical.blog"
    params:
      icon: "brand-github"
    weight: 10
  - identifier: "atom"
    name: "Feed"
    url: "/feed.xml"
    params:
      icon: "rss"
      newTab: false
    weight: 20
