main: []
social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/frawleyskid/nothingradical.blog"
    params:
      icon: "brand-github"
  - identifier: "rss"
    name: "RSS"
    url: "/feed.xml"
    params:
      icon: "rss"
