main:
  - identifier: "home"
    name: "Home"
    url: "/"
    weight: 10
    params:
      icon: "home"

social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/frawleyskid/nothingradical.blog"
    params:
      icon: "brand-github"
  - identifier: "subscribe"
    name: "Subscribe"
    url: "/feed.xml"
    params:
      icon: "rss"
