main: []
social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/frawleyskid/nothingradical.blog"
    params:
      icon: "brand-github"
    weight: 10
  - identifier: "mastodon"
    name: "Mastodon"
    url: "https://mastodon.lol/@frawley"
    params:
      icon: "brand-mastodon"
      rel: "me"
    weight: 20
  - identifier: "atom"
    name: "Feed"
    url: "/feed/"
    params:
      icon: "rss"
      newTab: false
    weight: 30
