mainSections: ["posts"]
rssFullContent: true
rssImage: "/images/logo-transparent.png"
favicon: "/images/logo-transparent.webp"

footer:
  since: 2020
  attribution: "Frawley"

comments:
  enabled: true
  provider: "hyvor"
  hyvor:
    siteid: 7134

dateFormat:
  published: "02 Jan 2006"
  lastUpdated: "02 Jan 2006 15:04 MST"

sidebar:
  subtitle: "A blog about queer stuff and neurodiversity"
  avatar:
    enabled: true
    local: false
    src: "/images/logo-transparent.webp"
    alt: "A rainbow infinity symbol"

article:
  math: false
  readingTime: true
  license:
    enabled: true
    default: "Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"

widgets:
  homepage:
    - type: "search"
    - type: "archives"
      params:
        limit: 5
    - type: "categories"
      params:
        limit: 10
    - type: "tag-cloud"
      params:
        limit: 20

opengraph:
  twitter:
    site: ""
    card: "summary"

defaultImage:
  opengraph:
    enabled: true
    local: false
    src: "/images/logo-transparent-padded.webp"

colorScheme:
  toggle: true
  default: "auto"

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

redirects:
  - from: "/feed"
    to: "/feed.xml"
    status: 301
  - from: "/tag/*/feed"
    to: "/tag/:splat/feed.xml"
    status: 301
  - from: "/category/*/feed"
    to: "/category/:splat/feed.xml"
    status: 301
