mainSections = ["posts"]
rssFullContent = true
favicon = "/images/neurodiversity-infinity.png"

[footer]
since = 2020

[dateFormat]
published = "02 Jan 2006"
lastUpdated = "02 Jan 2006 15:04 MST"

[sidebar]
subtitle = "A blog about queer stuff and neurodiversity"

[sidebar.avatar]
enabled = true
local = false
src = "/images/neurodiversity-infinity.png"

[article]
math = false
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-ND 4.0"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 20

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
